# Generated by Django 6.0.6 on 2026-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210624_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=40)),
                ('comentario', models.CharField(max_length=50)),
            ],
        ),
    ]
